/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f0xx.h>
#include "shift_reg.h"

/* DEFINITIONS */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/* MAIN CODE */
int main(void) {
	sct_init();
	sct_value(321);

	while(1) {
		for(uint16_t i = 0; i<1000 ; i+=111) {
				sct_value(i);
				for (volatile uint32_t i = 0; i < 100000; i++) {} // wait
			}
	}
} // int main(void)

