/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f0xx.h>

/* DEFINITIONS */
#define LED1_BIT (1<<4) //PA4
#define LED2_BIT (1<<0)//PB0
#define S1_BIT (1<<1) //PC1
#define S2_BIT (1<<0) //PC0, EXTI0

#define LED_TIME_BLINK 300 //ms
#define LED_TIME_SHORT 100 //ms
#define LED_TIME_LONG 1000 //ms
#define BUTTON_REFRESH_TIME 40 //ms


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* GLOBAL VARIABLES DECLARATION */
volatile uint32_t Tick;


/* USER FUNCTIONS */
// LED1 blinker
void blikac(void) {
	static uint32_t delay;

	if (Tick > delay + LED_TIME_BLINK) {
		GPIOA->ODR ^= LED1_BIT;
		delay = Tick;
	}
 }

// buttons operation
void tlacitka(void) {
	static uint32_t off_time;
	static uint32_t delay;
	static uint32_t old_s1;
	static uint32_t old_s2;

	// sample buttons every 40ms
	if (Tick > delay + BUTTON_REFRESH_TIME) {
		delay = Tick;
		//read buttons
		uint32_t new_s2 = GPIOC->IDR & S2_BIT;
		uint32_t new_s1 = GPIOC->IDR & S1_BIT;

		// short blink
		if (old_s2 && !new_s2) { // falling edge
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = LED2_BIT; // LED2 on
		}
		// long blink
		if (old_s1 && !new_s1) { // falling edge
			off_time = Tick + LED_TIME_LONG;
			GPIOB->BSRR = LED2_BIT; // LED2 on
		}
		old_s1 = new_s1;  // store actual value
		old_s2 = new_s2;
	}

	if (Tick > off_time) {
		GPIOB->BRR = LED2_BIT; // LED2 off
	}

}


/* MAIN CODE */
int main(void) {
	// SysTick init
	SysTick_Config(8000); // 1ms, 8MHz clk

	// PORT init
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable ports clock
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	// System configuration cntrl clk en
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	// Ext. interrupt init
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1


	while(1) {
		blikac();
		tlacitka();
	} // while(1)

} // int main(void)


/* INT HANDLERS */
//SysTicker increment
void SysTick_Handler(void) {
	Tick++;
}


// interrupt on S1 button
void EXTI0_1_IRQHandler(void) {
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit

	// Toggle LED2
	//GPIOB->ODR ^= LED2_BIT;
	}
 }
